//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAI_141249.Models
{
    using PAI_141249.Custom_Validation;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SingUp
    {
        public int IdTurnieju { get; set; }
        public int UserId { get; set; }

        [Display(Name = "Numer licencji")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Pole Numer licencji nie mo¿e byæ puste")]
        [CheckLicenseUnique]
        public string Licencja { get; set; }

        [Display(Name = "Ranking")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Pole Ranking nie mo¿e byæ puste")]
        [CheckRankUnique]
        public int Ranking { get; set; }
    }
}
