//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAI_141249.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using PAI_141249.Controllers;
    using PAI_141249.Custom_Validation;

    public partial class Tournament
    {
        public int IdTurnieju { get; set; }

        [Display(Name = "Nazwa")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Pole Nazwa nie mo¿e byæ puste")]
        public string Nazwa { get; set; }

        [Display(Name = "Dyscyplina")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Pole Dyscyplina nie mo¿e byæ puste")]
        public string Dyscyplina { get; set; }

        [Display(Name = "Czas")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Pole Czas nie mo¿e byæ puste")]
        public int Czas { get; set; }

        [Display(Name = "Szerokoœæ geograficzna")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Pole Szerokoœæ geograficzna nie mo¿e byæ puste")]
        public double MapaGoogleX { get; set; }

        [Display(Name = "Wysokoœæ geograficzna")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Pole Wysokoœæ geograficzna nie mo¿e byæ puste")]
        public double MapaGoogleY { get; set; }

        [Display(Name = "Limit")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Pole Limit nie mo¿e byæ puste")]
        public int Limit { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Pole Deadline nie mo¿e byæ puste")]
        [DataType(DataType.Date)]
        [CheckDateRangeAttribute]
        public System.DateTime Deadline { get; set; }

        [Display(Name = "Rozstawieni")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Pole Rozstawieni nie mo¿e byæ puste")]
        public int Rozstawieni { get; set; }

        [Display(Name = "Organizator")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Pole Organizator nie mo¿e byæ puste")]
        public string Organizator { get; set; }
    }
}
